
foobarbaz: &foobarbaz
  env:
    CIRRUS_WORKING_DIR: "~/flow-reporter-codeframe"
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn test

task:
  name: test (linux)
  container:
    image: node:10
  <<: *foobarbaz

task:
  name: test (osx)
  osx_instance:
    image: high-sierra-xcode-9.4.1
  yarn_script:
    - brew install yarn && node --version
  <<: *foobarbaz
