check_task:
  env:
    CIRRUS_WORKING_DIR: "~/flow-reporter-codeframe"
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  script: yarn test

win_task:
  windows_container:
    image: cirrusci/windowsservercore:2016
  script: yarn test
