
foobarbaz: &foobarbaz
  env:
    CIRRUS_WORKING_DIR: "~/flow-reporter-codeframe"
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn test

linux_task:
  <<: *foobarbaz
  container:
    image: node:10

osx_task:
  <<: *foobarbaz
  osx_instance:
    image: high-sierra-xcode-9.4.1
  yarn_script:
    - brew install yarn && node --version
